### ISSUE TITLE
Support configurable Jinja2 templates as PR body

### ISSUE THREAD

**Issue by GaretJax** [GaretJax/lancet#15]

**Comment by vxsx** [comment]
Not sure if it's better to create a separate issue for that, but it could be also great if PR file wouldn't get lost if PR was aborted on save.

**Comment by GaretJax** [comment]
I can handle both in the same run. Thanks for writing it down though... I've already been bitten by it myself.

**Comment by GaretJax** [comment]
Opened #18 to track remembering stuff across invocations. It may be a little more involving since I will have to keep state somewhere.

This one can thus be closed.
